config/routes.rb
Rails.application.routes.draw do
  resources :playlists do
    resources :tracks
  end
  root 'songs#index'

  resources :lyrics
  resources :songs
  resources :artists

  get "/list_songs", to: 'songs#list_songs'
  get "/list_yearly", to: 'songs#list_yearly'
  get "/list_artists", to: 'artists#list_artists'  
  get "/list_tracks/:playlist_id", to: 'tracks#list_tracks'
  get "/list_youtubes/:playlist_id", to: 'tracks#list_youtubes'
  get "/uploaded_songs", to: 'songs#uploaded_songs'
  get "/uploaded_rs500", to: 'songs#uploaded_rs500'
  get "/display", to: 'artists#display'    
  get "/player", to: 'artists#player'    



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy  
  default_scope {order('name asc')}
  scope :published, -> { where(chosen: true) }
  scope :by_name_asc, -> { order(name: :asc) }  
  scope :by_name_desc, -> { order(name: :desc) }    
  scope :by_songs, -> { order(charted_songs: :desc) }

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy, :display, :player]

  # GET /artists
  # GET /artists.json
  def index
    if params[:keywords].present?
      @keywords = params[:keywords]
      artist_search_term = ArtistSearchTerm.new(@keywords)
      @artists = Artist.where(
        artist_search_term.where_clause,
        artist_search_term.where_args).
        order(artist_search_term.order)
    else
      @artists = Artist.limit(15).by_songs
    end
  end

  def list_artists
    @artists = Artist.published.by_name_asc
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/1
  # GET /artists/1.json
  def display
    @songs = @artist.songs.selected.by_nbr_asc
  end

  def player
    @songs = @artist.songs.selected.by_nbr_asc
  end  

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name, :charted_songs, :image, :chosen)
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
  def destination(name)

      dest = 'http://www.last.fm/music/'+name

  end  
end

app/views/artists/_form.html.erb
<%= form_with(model: artist, local: true) do |form| %>
  <% if artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :artist_name %>
  </div>

  <div class="field">
    <%= form.label :chosen %><br>
    <%= form.check_box :chosen %>
  </div>

  <div class="field">
    <%= form.label :charted_songs %>
    <%= form.number_field :charted_songs, id: :artist_charted_songs %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :artist_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/artists/display.html.erb
<% content_for :title, @artist.name %>
<h3><%= @artist.name %></h3>
  <!-- start of loop -->
  <% @songs.each do |song| %>
    <!-- start of call-outs-container -->
    <div class="call-outs-container">
      <div class='call-out'>
          <p><%= song.nbr %></p>
      </div> 
      <div class='call-out'>
        <!-- start of youtube section -->
        <object>
          <param name="movie">
          <param name="wmode" value="transparent">
          <param name="allowFullScreen" value="true">
          <param name="allowScriptAccess" value="always">
          <embed <%= %[src=http://www.youtube.com/v/#{song.code}?rel=0] %>
                      type="application/x-shockwave-flash" allowscriptaccess="always"
                      allowfullscreen="true" wmode="transparent" width="185" height="105">
        </object>
        <!-- end of youtube section -->        
      </div>
      <div class='call-out'>
          <p><%= song.title %></p>
      </div> 
    </div> <!-- end of call-outs-container -->
  <% end %> <!-- end of loop -->

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>
<% content_for :title, 'Artists' %>
<h1>Artists</h1>
<section class="search-form">
  <%= form_for :songs, method: :get do |f| %>
    <div class="input-group input-group-md">
      <%= label_tag :keywords, nil, class: "sr-only" %>
      <%= text_field_tag :keywords, nil,
            placeholder: "Artist Name",
                  class: "form-control input-md" %>
      <span class="input-group-btn">
        <%= submit_tag "Find Artists",
              class: "btn btn-primary btn-md" %>
      </span>
    </div>
  <% end %>
</section>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Charted songs</th>
      <th>Image</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.name %></td>
        <td><%= artist.charted_songs %></td>
        <td><%= artist.image %></td>
        <td><%= link_to 'Show', artist %></td>
        <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
        <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Display', controller: :artists, action: :display,
        id: artist, target: "_new" %></td>
        <td><%= link_to 'Player', controller: :artists, action: :player,
        id: artist, target: "_blank" %></td>        
      </tr>

    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artist', new_artist_path %>

app/views/artists/list_artists.html.erb
<% content_for :title, 'Chosen Artists' %>
<h3>Songs by Artists</h3>

<table id="artists" class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Charted Songs</th>
      <th>Display</th>
    </tr>
  </thead>

  <tbody>
    <% nbr_of_artists = 0 %>
    <% @artists.each do |artist| %>
      <% nbr_of_artists = nbr_of_artists + 1 %>
      <tr>
        <td><%= artist.name %></td>
        <td><%= artist.charted_songs %></td>
        <td><%= link_to 'Display', controller: :artists, action: :display,
        id: artist, target: "_new" %></td>
        <td><%= link_to 'Player', controller: :artists, action: :player,
        id: artist, target: "_new" %></td>        
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= 'Number of artists =' + nbr_of_artists.to_s %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Back', artists_path %>

app/views/artists/player.html.erb
<% content_for :title, @artist.name %>
<h3><%= @artist.name %></h3>
    <!-- start of row -->
    <div class="row">
        <!-- start of loop -->
        <% @songs.each do |song| %>
            <!-- start of col -->
            <div class='col-xs-12 col-sm-6 col-md-4 col-lg-3'>
                <!-- start of card -->            
                <div class="card border-light">
                    <iframe <%= %[src=https://www.youtube.com/embed/#{song.code}] %> 
                        allowfullscreen allowtransparency allow="autoplay"></iframe>
                    <!-- start of card-body -->                            
                    <div class='card-body'>
                        <h5 class="card-title text-center mb-1"><%= song.title %></h5>
                    </div> 
                    <!-- end of card-body -->                            
                </div>
                <!-- end of card -->                            
            </div> 
            <!-- end of col -->
        <% end %> 
        <!-- end of loop -->
    </div>
    <!-- end of row -->

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>
<% content_for :title, 'Show Artist' %>
<p>
  <strong>Name:</strong>
  <%= @artist.name %>
</p>

<p>
  <strong>Charted songs:</strong>
  <%= @artist.charted_songs %>
</p>

<p>
  <strong>Image:</strong>
  <% if @artist.image.present? %>
    <%= image_tag @artist.image %>
  <% end %>
</p>

<p>
  <b>Destination:</b>
	<%= link_to(destination(@artist.name), destination(@artist.name), :target => "_new") %>
</p>

<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>