config/routes.rb
Rails.application.routes.draw do
  resources :playlists do
    resources :tracks
  end
  root 'songs#index'

  resources :lyrics
  resources :songs
  resources :artists

  get "/list_songs", to: 'songs#list_songs'
  get "/list_yearly", to: 'songs#list_yearly'
  get "/list_artists", to: 'artists#list_artists'  
  get "/list_tracks/:playlist_id", to: 'tracks#list_tracks'
  get "/list_youtubes/:playlist_id", to: 'tracks#list_youtubes'
  get "/uploaded_songs", to: 'songs#uploaded_songs'
  get "/uploaded_rs500", to: 'songs#uploaded_rs500'
  get "/display", to: 'artists#display'    
  get "/player", to: 'artists#player'    



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  has_one :lyric
  mount_uploader :mp3, Mp3Uploader

  scope :selected, -> { where('nbr < 99') }
  scope :by_nbr_asc, -> { order(nbr: :asc) }

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    if params[:keywords].present?
      @keywords = params[:keywords]
      song_search_term = SongSearchTerm.new(@keywords)
      @songs = Song.joins(:artist).where(
        song_search_term.where_clause,
        song_search_term.where_args).
        order(song_search_term.order)
    else
      @songs = Song.limit(100).order(year: :asc, rank: :asc)
    end
  end

  def list_songs
    @songs = Song.where("will_upload = True").order(publish_date: :asc)
  end

  def list_yearly
    @songs = Song.where("year = 1979 AND code <> '' AND rank <= 100 AND nbr=99")
    .order(rank: :asc)
  end

  def uploaded_songs
    @songs = Song.where("uploaded = True").order(year: :asc, rank: :asc)
  end

  def uploaded_rs500
    @songs = Song.where("rs500 < 999 AND uploaded = True").order(id: :desc)
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:year, :rank, :title, :artist_id, :code, :mp3, :duration,
      :will_upload, :uploaded, :publish_date, :playlist, :nbr, :views)
    end
end

app/helpers/songs_helper.rb
module SongsHelper

  def seconds_to_time(duration)
		minutes = (duration / 60).to_i
    if (minutes > 60)
      hours = (minutes / 60).to_i
      minutes = minutes - (hours*60)
    end
		seconds = duration - (minutes * 60)
		minutes.to_s+":"+seconds.to_s.rjust(2, '0')
	end

  def seconds_to_hour(duration)
		minutes = (duration / 60).to_i
    hours = 0
    if (minutes > 60)
      hours = (minutes / 60).to_i
      minutes = minutes - (hours*60)
    end
		seconds = duration - ((hours * 3600) + (minutes * 60))
		hours.to_s+":"+minutes.to_s.rjust(2, '0')+":"+seconds.to_s.rjust(2, '0')
	end

end

app/views/songs/_form.html.erb
<% content_for :title, song.title %>
<%= form_with(model: song, local: true) do |form| %>
  <% if song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year, id: :song_year %>
  </div>

  <div class="field">
    <%= form.label :rank %>
    <%= form.number_field :rank, id: :song_rank %>
  </div>


  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :song_title %>
  </div>

  <div class="field">
    <%= form.label :artist_id %><br />
    <%= form.collection_select :artist_id, Artist.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :nbr %>
    <%= form.number_field :nbr, id: :song_nbr %>
  </div>

  <div class="field">
    <%= form.label :will_upload %>
    <%= form.check_box :will_upload, id: :song_will_upload %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

  <div class="field">
    <%= form.label :views %>
    <%= form.number_field :views, id: :song_views %>
  </div>
  
  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code, id: :song_code %>
  </div>

  <div class="field">
    <%= form.label :mp3 %><br />
    <%= form.file_field :mp3 %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration, id: :song_duration %>
  </div>



  <div class="field">
    <%= form.label :uploaded %>
    <%= form.check_box :uploaded, id: :song_uploaded %>
  </div>

  <div class="field">
    <%= form.label :playlist %>
    <%= form.check_box :playlist, id: :song_playlist %>
  </div>

  <div class="field">
    <%= form.label :publish_date %>
    <%= form.date_select :publish_date, order: [:day, :month, :year], :start_year => 2006, :end_year => 2019 %>
  </div>


<% end %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>
<% content_for :title, 'Songs' %>
<h1>Songs</h1>
<section class="search-form">
  <%= form_for :songs, method: :get do |f| %>
    <div class="input-group input-group-md">
      <%= label_tag :keywords, nil, class: "sr-only" %>
      <%= text_field_tag :keywords, nil,
            placeholder: "Song Title, Artist Name, or Year",
                  class: "form-control input-md" %>
      <span class="input-group-btn">
        <%= submit_tag "Find Songs",
              class: "btn btn-primary btn-md" %>
      </span>
    </div>
  <% end %>
</section>
<table id="songs" class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Year</th>
      <th>Rank</th>
      <th>Nbr</th>      
      <th>Title</th>
      <th>Artist</th>
      <%# <th>Time</th> %>
      <th>Views</th>
      <th>S</th>
      <th>E</th>
      <th>youtu</th>
      <th>mp3</th>
      <th>lyric</th>
      <%# <th>Will</th> %>
      <th>Upload</th>
      <th>D</th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.year %></td>
        <td><%= song.rank %></td>
        <td><%= song.nbr %></td>        
        <td><%= song.title %></td>
        <td><%= song.artist.name %></td>
        <%# # <td><%= seconds_to_time(song.duration) </td> %>
        <td><%= number_to_human(song.views, :format => '%n%u', :precision => 2, :units => { :thousand => 'K', :million => 'M', :billion => 'B' }) %></td>

        <td><%= link_to 'S', song, target: "_new" %></td>
        <td><%= link_to 'E', edit_song_path(song), target: "_new" %></td>

        <td><%= song.code.present? %></td>
        <td><%= song.mp3.present? %></td>
        <td><%= song.lyric.present? %></td>
        <%# <td><%= song.will_upload </td> %>
        <td><%= song.uploaded %></td>
        <td><%= link_to 'D', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path %>

app/views/songs/list_songs.html.erb
<p id="notice"><%= notice %></p>
<% content_for :title, 'Lists' %>
<h3>Songs That Will Be Uploaded</h3>

<table id="songs" class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Year</th>
      <th>Rank</th>
      <th>Title</th>
      <th>Artist</th>
      <th>mp3</th>
      <th>code</th>
      <th>upload</th>
      <th>Publish</th>
      <th>S</th>
      <th>E</th>
      <th>D</th>
    </tr>
  </thead>

  <tbody>
    <% nbr_of_songs = 0 %>
    <% @songs.each do |song| %>
      <% nbr_of_songs = nbr_of_songs + 1 %>
      <tr>
        <td><%= song.year %></td>
        <td><%= song.rank %></td>
        <td><%= song.title %></td>
        <td><%= song.artist.name %></td>
        <td><%= song.mp3.present? %></td>
        <td><%= song.code.present? %></td>
        <td><%= song.uploaded %></td>

        <td><%= song.publish_date %></td>
        <td><%= link_to 'S', song, target: "_new" %></td>
        <td><%= link_to 'E', edit_song_path(song), target: "_new" %></td>
        <td><%= link_to 'D', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= 'Number of songs =' + nbr_of_songs.to_s %>
<br>
<%= link_to 'New Song', new_song_path %>

app/views/songs/list_yearly.html.erb
<h3><%= 'Billboard 1979' %></h3>
    <!-- start of row -->
    <div class="row">
        <!-- start of loop -->
        <% @songs.each do |song| %>
            <!-- start of col -->
            <div class='col s12 m6 l3'>
                <!-- start of card -->            
                <div class="card teal">
                    <div class="video-container">
                        <iframe <%= %[src=https://www.youtube.com/embed/#{song.code}] %> 
                        frameborder="0" allowfullscreen allow="autoplay"></iframe>

                    </div>
                    <!-- start of card-content -->                            
                    <div class='card-content'>
                        <span class="card-title center-align truncate white-text"><%= song.title %></h5>
                        <p class="center-align truncate white-text"><%=  song.artist.name %></p>                        
                    </div> 
                    <!-- end of card-content -->                            
                </div>
                <!-- end of card -->                            
            </div> 
            <!-- end of col -->
        <% end %> 
        <!-- end of loop -->
    </div>
    <!-- end of row -->

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<% content_for :title, @song.title %>
<div class="row">
  <!-- start of left column -->
  <div class="col-lg-6 col-md-6 col-xs-12">
    <div class="card card-inverse" style="background:#000;">
      <!-- start of youtube section -->
      <div class="card-block" style="align:center;">
        <object>
          <param name="movie">
          <param name="wmode" value="transparent">
          <param name="allowFullScreen" value="true">
          <param name="allowScriptAccess" value="always">
          <embed <%= %[src=http://www.youtube.com/v/#{@song.code}?version=3] %>
            type="application/x-shockwave-flash" allowscriptaccess="always"
            allowfullscreen="true" wmode="transparent" width="400" height="200">
        </object>
      </div> <!-- end of card-block -->
    </div> <!-- end of card -->
    <!-- end of youtube section -->
    <!-- start of summary table section -->
    <div class="card text-center text-white bg-dark">
      <div class="card-header"><%= @song.title %></div>
      <div class="card-block">
        <table class="table">
          <tbody>
            <tr>
              <td>Year:</td>
              <td><%= @song.year %></td>
            </tr>
            <tr>
              <td>Rank:</td>
              <td><%= @song.rank %></td>
            </tr>
            <tr>
              <td>Duration:</td>
              <td><%= seconds_to_time(@song.duration) %></td>
            </tr>
            <tr>
              <td>Views:</td>
              <td><%= number_to_human(@song.views, :format => '%n%u', :precision => 2, :units => { :thousand => 'K', :million => 'M', :billion => 'B' }) %></td>
            </tr>
                                    <%# <tr>
              <td>Publish Date:</td> 
              <td><%= @song.publish_date </td>
            </tr> %>

          </tbody>
        </table>
      </div> <!-- end of card-block -->
    </div> <!-- end of card -->
    <!-- end of summary table section -->
    <!-- start of image section -->
    <div class="card text-center text-white bg-dark">
      <div class="card-header"><%= @song.artist.name %></div>
  		<%= image_tag @song.artist.image, class: "card-img-top img-fluid" %>
      <div class="card-footer">
        <% wiki_artist='https://en.wikipedia.org/wiki/'+CGI.escape(@song.artist.name.tr(' ','_')) %>
    		<%= link_to('Artist Wiki', wiki_artist, :target => "_new", class: "btn btn-info") %>
      </div>
    </div> <!-- enf of card -->
    <!-- end of image section -->
  </div> <!-- end of Left col -->
  <!-- start of lyrics column -->
  <div class="col-lg-6 col-md-6 col-xs-12">
    <div class="card text-center text-white bg-dark">
      <div class="card-header"><%= audio_tag(@song.mp3, autoplay: false, controls: true, preload: "auto") %></div>
      <div class="card-block">
        <span class="h4 card-title"><%= @song.title %></span>
        <% if Lyric.exists?(:song_id=>@song.id) %>
      		<%= simple_format(@song.lyric.content) %>
      	<% else %>
      		<%= 'No lyric' %>
      	<% end %>
        <% wiki_song='https://en.wikipedia.org/wiki/' + CGI.escape(@song.title.tr(' ','_')) %>
        <%= link_to('Read More', wiki_song, :target => "_new", class: "btn btn-primary") %>
      </div> <!-- end of card block -->
    </div> <!-- end of card -->
  </div> <!-- end of lyrics col -->
</div> <!-- end of row -->
<!-- begin of delete section -->
<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>
<!-- end of delete section -->
<script type="text/javascript" src="js/jquery.min.js"></script>
<script type="text/javascript" src="js/tether.min.js"></script>
<script type="text/javascript" src="js/bootstrap.js"></script>

app/views/songs/uploaded_rs500.html.erb
<p id="notice"><%= notice %></p>
<% content_for :title, 'RS500 Songs' %>
<h3>Uploaded Songs</h3>

<table id="uploaded_songs" class="display table table-striped table-hover">
  <thead>
    <tr>
      <th>Rs500</th>
      <th>Year</th>
      <th>Rank</th>
      <th>Title</th>
      <th>Artist</th>
      <th>Views</th>
      <th>Id</th>
      <th>Show</th>
    </tr>
  </thead>

  <tbody>
    <% number_of_songs = 0 %>
    <% total_time = 0 %>
    <% total_views = 0 %>
    <% @songs.each do |song| %>
      <% number_of_songs = number_of_songs + 1 %>
      <% total_time = total_time + song.duration %>
      <% total_views = total_views + song.views %>
      <tr>
        <td><%= song.rs500 %></td>
        <td><%= song.year %></td>
        <td><%= song.rank %></td>
        <td class="title"><%= song.title %></td>
        <td class="name"><%= song.artist.name %></td>
        <%# <td><%= seconds_to_time(song.duration) </td> %>
        <td class="views"><%= song.views %></td>
        <td class="id"><%= song.id %></td>
        <% url_song = 'http://www.santiwebsite.com/songs/b' + song.year.to_s[2,3] + song.rank.to_s.rjust(2, '0') + '.html' %>
        <td><%= link_to('Show', url_song, :target => "_new", class: "btn btn-primary") %></td>
      </tr>
    <% end %>

  </tbody>
</table>
<p>
<span><%= 'Number of Songs = ' + number_of_songs.to_s %></span>
<span><%= 'Total Duration = ' + seconds_to_hour(total_time) %></span>
<span><%= 'Total Views = ' + number_to_human(total_views, :format => '%n%u', :precision => 2, :units => { :thousand => 'K', :million => 'M', :billion => 'B' }) %></span>
</p>
<script type="text/javascript" src="js/tether.min.js"></script>
<script type="text/javascript" src="js/bootstrap.js"></script>

app/views/songs/uploaded_songs.html.erb
<p id="notice"><%= notice %></p>
<% content_for :title, 'Uploaded Songs' %>
<h3>Uploaded Songs</h3>

<table id="uploaded_songs" class="display table table-striped table-hover">
  <thead>
    <tr>
      <th>Year</th>
      <th>Rank</th>
      <th>Title</th>
      <th>Artist</th>
      <th>Views</th>
      <th>Show</th>
    </tr>
  </thead>

  <tbody>
    <% number_of_songs = 0 %>
    <% total_time = 0 %>
    <% total_views = 0 %>
    <% @songs.each do |song| %>
      <% number_of_songs = number_of_songs + 1 %>
      <% total_time = total_time + song.duration %>
      <% total_views = total_views + song.views %>
      <tr>
        <td><%= song.year %></td>
        <td><%= song.rank %></td>
        <td class="title"><%= song.title %></td>
        <td class="name"><%= song.artist.name %></td>
        <%# <td><%= seconds_to_time(song.duration) </td> %>
        <td class="views"><%= song.views %></td>
        <% url_song = 'b' + song.year.to_s[2,3] + song.rank.to_s.rjust(2, '0') + '.html' %>
        <td><%= link_to('Show', url_song, :target => "_new", class: "btn btn-primary") %></td>
      </tr>
    <% end %>

  </tbody>
</table>
<p>
<span><%= 'Number of Songs = ' + number_of_songs.to_s %></span>
<span><%= 'Total Duration = ' + seconds_to_hour(total_time) %></span>
<span><%= 'Total Views = ' + number_to_human(total_views, :format => '%n%u', :precision => 2, :units => { :thousand => 'K', :million => 'M', :billion => 'B' }) %></span>
</p>
<script type="text/javascript" src="js/tether.min.js"></script>
<script type="text/javascript" src="js/bootstrap.js"></script>