config/routes.rb
Rails.application.routes.draw do
  resources :playlists do
    resources :tracks
  end
  root 'songs#index'

  resources :lyrics
  resources :songs
  resources :artists

  get "/list_songs", to: 'songs#list_songs'
  get "/list_yearly", to: 'songs#list_yearly'
  get "/list_artists", to: 'artists#list_artists'  
  get "/list_tracks/:playlist_id", to: 'tracks#list_tracks'
  get "/list_youtubes/:playlist_id", to: 'tracks#list_youtubes'
  get "/uploaded_songs", to: 'songs#uploaded_songs'
  get "/uploaded_rs500", to: 'songs#uploaded_rs500'
  get "/display", to: 'artists#display'    
  get "/player", to: 'artists#player'    



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  has_many :tracks, dependent: :destroy
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]

  # GET /playlists
  # GET /playlists.json
  def index
    @playlists = Playlist.all
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists
  # POST /playlists.json
  def create
    @playlist = Playlist.new(playlist_params)

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: 'Playlist was successfully created.' }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1
  # PATCH/PUT /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to @playlist, notice: 'Playlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to playlists_url, notice: 'Playlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def playlist_params
      params.require(:playlist).permit(:name, :artists)
    end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_form.html.erb
<%= form_with(model: playlist, local: true) do |form| %>
  <% if playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
      <% playlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :playlist_name %>
  </div>

  <div class="field">
    <%= form.label :artists %>
    <%= form.text_field :artists, id: :playlist_artists %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/playlists/edit.html.erb
<h1>Editing Playlist</h1>

<%= render 'form', playlist: @playlist %>

<%= link_to 'Show', @playlist %> |
<%= link_to 'Back', playlists_path %>

app/views/playlists/index.html.erb
<p id="notice"><%= notice %></p>
<% content_for :title, 'Playlists' %>
<h1>Playlists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Artists</th>
      <th>Tracks</th>

      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @playlists.each do |playlist| %>
      <tr>
        <td><%= playlist.name %></td>
        <td><%= playlist.artists %></td>
        <td><%= playlist.tracks.count %></td>
        <td><%= link_to 'Show', playlist %></td>
        <td><%= link_to 'Edit', edit_playlist_path(playlist) %></td>
        <td><%= link_to 'Tracks', playlist_tracks_path(playlist) %></td>
        <td><%= link_to 'Website', "/list_tracks/#{playlist.id}" %></td>
        <td><%= link_to 'Youtube', "/list_youtubes/#{playlist.id}" %></td>
        <td><%= link_to 'Destroy', playlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Playlist', new_playlist_path %>

app/views/playlists/new.html.erb
<h1>New Playlist</h1>

<%= render 'form', playlist: @playlist %>

<%= link_to 'Back', playlists_path %>

app/views/playlists/show.html.erb
<p id="notice"><%= notice %></p>
<% content_for :title, @playlist.name %>
<p>
  <strong>Name:</strong>
  <%= @playlist.name %>
</p>

<p>
  <strong>Artists:</strong>
  <%= @playlist.artists %>
</p>
<h3>Tracks</h3>
<table>
  <tr>
    <th>Position</th>
    <th>Title</th>
    <th>Artist</th>
  </tr>
  <% for track in @playlist.tracks %>
    <tr>
      <td><%= track.position %></td>
      <td><%= track.song.title %></td>
      <td><%= track.song.artist.name %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Edit', edit_playlist_path(@playlist) %> |
<%= link_to 'Tracks', playlist_tracks_path(@playlist) %> |
<%= link_to 'Back', playlists_path %>